# permissions for end users to edit democlusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: democluster-editor-role
rules:
- apiGroups:
  - demo.demo.godocument.com
  resources:
  - democlusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.demo.godocument.com
  resources:
  - democlusters/status
  verbs:
  - get
